//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionKermesseGrupo2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CategoriaGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaGasto()
        {
            this.Gasto = new HashSet<Gasto>();
        }

        [Display(Name = "Codigo")]
        public int idCatGasto { get; set; }

        [Display(Name = "Nombre de Categoria")]
        [Required]
        [StringLength(45)]
        [DataType(DataType.Text)]
        public string nombreCategoria { get; set; }

        [Display(Name = "Desc Categoria")]
        [Required]
        [StringLength(100)]
        [DataType(DataType.Text)]
        public string descripcion { get; set; }

        [Display(Name = "Estado Categoria")]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
    }
}
