//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionKermesseGrupo2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IngresoComunidadDet
    {
        [Display(Name = "Codigo")]
        public int idIngresoComunidadDet { get; set; }

        [Display(Name = "Codigo Ingreso")]
        [Required]
        public int ingresoComunidad { get; set; }

        [Display(Name = "Bono")]
        [Required]
        public int bono { get; set; }

        [Display(Name = "Denominacion")]
        [Required]
        [StringLength(45)]
        public string denominacion { get; set; }

        [Display(Name = "Cantidad")]
        [Required]
        public int cantidad { get; set; }

        [Display(Name = "Subtotal del Bono")]
        [Required]
        public double subTotalBono { get; set; }
    
        public virtual ControlBono ControlBono { get; set; }
        public virtual IngresoComunidad IngresoComunidad1 { get; set; }

        public virtual Comunidad Comunidad1 { get; set; }
    }
}
