//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionKermesseGrupo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwIngresoKermesse
    {
        public int idKermesse { get; set; }
        public string NombreKermesse { get; set; }
        public string Producto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public double subTotalBono { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
