//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionKermesseGrupo2.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD:SolucionKermesseGrupo2/Models/VwListaPrecio.cs
    public partial class VwListaPrecio
    {
        public int idListaPrecio { get; set; }
        public string Kermesse { get; set; }
        public string Lista { get; set; }
        public string descripcion { get; set; }
=======
    public partial class VwRolOpciones
    {
        public int Id { get; set; }
        public string Rol_Desc { get; set; }
        public string Opc_Desc { get; set; }
>>>>>>> master:SolucionKermesseGrupo2/Models/VwRolOpciones.cs
    }
}
