//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionKermesseGrupo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwListaPrecio
    {
        public int idListaPrecio { get; set; }
        public int idListaPrecioDet { get; set; }
        public int idKermesse { get; set; }
        public int idCatProd { get; set; }
        public string NombrePrecio { get; set; }
        public string DescPrecio { get; set; }
        public double precioVenta { get; set; }
        public string NombreKermesse { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<int> CantidadProducto { get; set; }
        public string NombreCategoria { get; set; }
        public int estado { get; set; }
    }
}
